Introduce sharding

diff --git a/.github/workflows/snapshots.yml b/.github/workflows/snapshots.yml
--- a/.github/workflows/snapshots.yml
+++ b/.github/workflows/snapshots.yml
@@ -44,6 +44,10 @@ on:
       cache_restore_keys:
         description: pass to restore-keys of actions/cache@v4
         type: string
+      shard_count:
+        description: append argument --shard=1/n to the snapshots_command
+        type: number
+        default: 4
     secrets:
       your_repo_github_token:
         required: true
@@ -53,23 +57,21 @@ on:
         required: false
 
 jobs:
-  snapshots:
+  init:
     runs-on: ubuntu-latest
-    container:
-      image: mcr.microsoft.com/playwright:${{ inputs.playwright_image_tag }}
-    env:
-      GPR_READ_TOKEN: ${{ secrets.env_gpr_read_token }}
+    outputs:
+      shard_indexes_json: ${{ steps.vars.outputs.shard_indexes_json }}
+      vrt_diff_temp_branch: ${{ steps.vars.outputs.vrt_diff_temp_branch }}
+      vrt_diff_dirname: ${{ steps.vars.outputs.vrt_diff_dirname }}
+      vrt_diff_workspace: ${{ steps.vars.outputs.vrt_diff_workspace }}
+      vrt_diff_base_branch: ${{ steps.vars.outputs.vrt_diff_base_branch }}
+      base_sha: ${{ steps.vars.outputs.base_sha }}
+      head_sha: ${{ steps.vars.outputs.head_sha }}
+      required_base_snapshots: ${{ steps.checkouts.outputs.required_base_snapshots }}
     steps:
-      - name: Set safe directory for permission on docker container
-        run: git config --global --add safe.directory "$(pwd)"
-      - name: Clone your repository
-        uses: actions/checkout@v4
-        with:
-          fetch-depth: 0
-          repository: ${{ inputs.your_repo }}
-          token: ${{ secrets.your_repo_github_token }}
       - name: Setup variables
         run: |
+          echo "shard_indexes_json=$(seq ${{ inputs.shard_count }} | jq -cs 'map("\(.)")')" > $GITHUB_OUTPUT
           echo "vrt_diff_temp_branch=diff" >> $GITHUB_OUTPUT
           echo "vrt_diff_dirname=diff" >> $GITHUB_OUTPUT
           if [ "${{ github.event_name }}" = "pull_request" ]; then
@@ -83,17 +85,46 @@ jobs:
             echo "base_sha=${{ github.sha }}" >> $GITHUB_OUTPUT
           fi
         id: vars
+      - name: Clone vrt repository
+        uses: actions/checkout@v4
+        with:
+          repository: ${{ inputs.vrt_repo }}
+          ref: ${{ steps.vars.outputs.vrt_diff_base_branch }}
+          path: ${{ steps.vars.outputs.vrt_diff_workspace }}
+          token: ${{ secrets.vrt_repo_github_token }}
+        continue-on-error: true
+        id: base
+      - name: Set required base snapshots on failure
+        run: echo "required_base_snapshots=true" >> $GITHUB_OUTPUT
+        if: steps.base.outcome == 'failure' || inputs.force_update_base_snapshots
+        id: checkouts
+
+  base:
+    if: needs.init.outputs.required_base_snapshots
+    needs: init
+    runs-on: ubuntu-latest
+    container:
+      image: mcr.microsoft.com/playwright:${{ inputs.playwright_image_tag }}
+    env:
+      GPR_READ_TOKEN: ${{ secrets.env_gpr_read_token }}
+    strategy:
+      matrix:
+        shard_index: ${{ fromJson(needs.init.outputs.shard_indexes_json) }}
+        shard_total:
+          - ${{ inputs.shard_count }}
+    steps:
+      - name: Set safe directory for permission on docker container
+        run: git config --global --add safe.directory "$(pwd)"
+      - name: Clone your repository
+        uses: actions/checkout@v4
+        with:
+          repository: ${{ inputs.your_repo }}
+          token: ${{ secrets.your_repo_github_token }}
+          ref: ${{ needs.init.outputs.base_sha }}
       - name: Setup node.js
         uses: actions/setup-node@v4
         with:
           node-version: ${{ inputs.node_version }}
-      - name: Clone vrt repository
-        uses: actions/checkout@v4
-        with:
-          fetch-depth: 0
-          repository: ${{ inputs.vrt_repo }}
-          path: ${{ steps.vars.outputs.vrt_diff_workspace }}
-          token: ${{ secrets.vrt_repo_github_token }}
       - name: Restore some caches
         uses: actions/cache@v4
         with:
@@ -101,68 +132,141 @@ jobs:
           path: ${{ inputs.cache_paths }}
           restore-keys: ${{ inputs.cache_restore_keys }}
         if: inputs.cache_key
-      - name: Checkout vrt by base branch
-        run: |
-          cd ${{ steps.vars.outputs.vrt_diff_workspace }}
-          git config user.name  "GitHub Action"
-          git config user.email "action@github.com"
-          if [ "${{ inputs.force_update_base_snapshots }}" = "true" ] || ! git checkout ${{ steps.vars.outputs.vrt_diff_base_branch }}; then
-            git checkout -b ${{ steps.vars.outputs.vrt_diff_base_branch }}
-            echo "required_base_snapshots=true" >> $GITHUB_OUTPUT
-          fi
-        id: checkouts
-      - name: Checkout base
-        run: git checkout ${{ steps.vars.outputs.base_sha }}
-        if: steps.checkouts.outputs.required_base_snapshots
       - name: Install npm modules on base
         run: ${{ inputs.install_command }}
-        if: steps.checkouts.outputs.required_base_snapshots
       - name: Take snapshots on base
-        run: ${{ inputs.snapshots_command }}
-        if: steps.checkouts.outputs.required_base_snapshots
-      - name: Copy snapshots to vrt on base
-        run: cp -r ${{ inputs.snapshots_dirpath }} ${{ steps.vars.outputs.vrt_diff_workspace }}/${{ steps.vars.outputs.vrt_diff_dirname }}
-        if: steps.checkouts.outputs.required_base_snapshots
-      - name: Push snapshots of base
+        run: ${{ inputs.snapshots_command }} --shard ${{ matrix.shard_index }}/${{ matrix.shard_total }}
+      - name: Upload base snapshots
+        uses: actions/upload-artifact@v4
+        with:
+          name: base_snapshots_${{ matrix.shard_index }}
+          path: ${{ inputs.snapshots_dirpath }}
+      - name: Upload test-results on failure for debug
+        uses: actions/upload-artifact@v4
+        with:
+          name: test-results
+          path: test-results
+        if: failure()
+
+  commit_base:
+    needs: [init, base]
+    runs-on: ubuntu-latest
+    steps:
+      - name: Clone vrt repository
+        uses: actions/checkout@v4
+        with:
+          repository: ${{ inputs.vrt_repo }}
+          path: ${{ needs.init.outputs.vrt_diff_workspace }}
+          token: ${{ secrets.vrt_repo_github_token }}
+      - name: Download base snapshots
+        uses: actions/download-artifact@v4
+        with:
+          path: ${{ needs.init.outputs.vrt_diff_workspace }}/${{ needs.init.outputs.vrt_diff_dirname }}
+          pattern: base_snapshots_*
+          merge-multiple: true
+      - name: Push vrt by base branch
         run: |
-          cd ${{ steps.vars.outputs.vrt_diff_workspace }}
-          git add ${{ steps.vars.outputs.vrt_diff_dirname }}
+          cd ${{ needs.init.outputs.vrt_diff_workspace }}
+          git config user.name  "GitHub Action"
+          git config user.email "action@github.com"
+          git checkout -b ${{ needs.init.outputs.vrt_diff_base_branch }}
+          git add ${{ needs.init.outputs.vrt_diff_dirname }}
           git commit -m "Update screenshots [ci skip]"
-          git push origin HEAD:${{ steps.vars.outputs.vrt_diff_base_branch }} -f
-        if: steps.checkouts.outputs.required_base_snapshots
+          git push origin HEAD:${{ needs.init.outputs.vrt_diff_base_branch }} -f
+
+  head:
+    if: ${{ github.event_name == 'pull_request' && !cancelled() && !failure() }}
+    needs: [init, commit_base]
+    runs-on: ubuntu-latest
+    container:
+      image: mcr.microsoft.com/playwright:${{ inputs.playwright_image_tag }}
+    env:
+      GPR_READ_TOKEN: ${{ secrets.env_gpr_read_token }}
+    strategy:
+      matrix:
+        shard_index: ${{ fromJson(needs.init.outputs.shard_indexes_json) }}
+        shard_total:
+          - ${{ inputs.shard_count }}
+    steps:
+      - name: Set safe directory for permission on docker container
+        run: git config --global --add safe.directory "$(pwd)"
+      - name: Clone your repository
+        uses: actions/checkout@v4
+        with:
+          repository: ${{ inputs.your_repo }}
+          token: ${{ secrets.your_repo_github_token }}
+          ref: ${{ needs.init.outputs.head_sha }}
+      - name: Clone vrt repository
+        uses: actions/checkout@v4
+        with:
+          repository: ${{ inputs.vrt_repo }}
+          ref: ${{ needs.init.outputs.vrt_diff_base_branch }}
+          path: ${{ needs.init.outputs.vrt_diff_workspace }}
+          token: ${{ secrets.vrt_repo_github_token }}
       - name: Copy base snapshots from vrt
-        run: cp -r ${{ steps.vars.outputs.vrt_diff_workspace }}/${{ steps.vars.outputs.vrt_diff_dirname }} ${{ inputs.snapshots_dirpath }}
-        if: steps.checkouts.outputs.required_base_snapshots == false
-      - name: Checkout head
-        run: git checkout ${{ steps.vars.outputs.head_sha }}
-        if: github.event_name == 'pull_request'
+        run: cp -r ${{ needs.init.outputs.vrt_diff_workspace }}/${{ needs.init.outputs.vrt_diff_dirname }} ${{ inputs.snapshots_dirpath }}
+      - name: Setup node.js
+        uses: actions/setup-node@v4
+        with:
+          node-version: ${{ inputs.node_version }}
+      - name: Restore some caches
+        uses: actions/cache@v4
+        with:
+          key: ${{ inputs.cache_key }}
+          path: ${{ inputs.cache_paths }}
+          restore-keys: ${{ inputs.cache_restore_keys }}
+        if: inputs.cache_key
       - name: Install npm modules on head
         run: ${{ inputs.install_command }}
-        if: github.event_name == 'pull_request'
       - name: Take snapshots on head
-        run: ${{ inputs.snapshots_command }}
-        if: github.event_name == 'pull_request'
-      - name: Copy snapshots to vrt on head
-        run: |
-          rm -rf ${{ steps.vars.outputs.vrt_diff_workspace }}/${{ steps.vars.outputs.vrt_diff_dirname }}
-          cp -r ${{ inputs.snapshots_dirpath }} ${{ steps.vars.outputs.vrt_diff_workspace }}/${{ steps.vars.outputs.vrt_diff_dirname }}
-        if: github.event_name == 'pull_request'
+        run: ${{ inputs.snapshots_command }} --shard ${{ matrix.shard_index }}/${{ matrix.shard_total }}
+      - name: Upload head snapshots
+        uses: actions/upload-artifact@v4
+        with:
+          name: head_snapshots_${{ matrix.shard_index }}
+          path: ${{ inputs.snapshots_dirpath }}
+      - name: Upload test-results on failure for debug
+        uses: actions/upload-artifact@v4
+        with:
+          name: test-results
+          path: test-results
+        if: failure()
+
+  commit_head:
+    if: ${{ !cancelled() && !failure() }}
+    needs: [init, commit_base, head]
+    runs-on: ubuntu-latest
+    steps:
+      - name: Clone vrt repository
+        uses: actions/checkout@v4
+        with:
+          repository: ${{ inputs.vrt_repo }}
+          ref: ${{ needs.init.outputs.vrt_diff_base_branch }}
+          path: ${{ needs.init.outputs.vrt_diff_workspace }}
+          token: ${{ secrets.vrt_repo_github_token }}
+      - name: Download base snapshots
+        uses: actions/download-artifact@v4
+        with:
+          path: ${{ needs.init.outputs.vrt_diff_workspace }}/${{ needs.init.outputs.vrt_diff_dirname }}
+          pattern: head_snapshots_*
+          merge-multiple: true
       - name: Push snapshots of head
         run: |
-          cd ${{ steps.vars.outputs.vrt_diff_workspace }}
-          git add -N ${{ steps.vars.outputs.vrt_diff_dirname }}
-          if ! git diff --exit-code --quiet ${{ steps.vars.outputs.vrt_diff_dirname }}
+          cd ${{ needs.init.outputs.vrt_diff_workspace }}
+          git config user.name  "GitHub Action"
+          git config user.email "action@github.com"
+          git add -N ${{ needs.init.outputs.vrt_diff_dirname }}
+          if ! git diff --exit-code --quiet ${{ needs.init.outputs.vrt_diff_dirname }}
           then
-            git add ${{ steps.vars.outputs.vrt_diff_dirname }}
+            git add ${{ needs.init.outputs.vrt_diff_dirname }}
             echo "added_count=$(git diff HEAD --diff-filter=A --name-only | wc -l | xargs)" >> $GITHUB_OUTPUT
             echo "changed_count=$(git diff HEAD --diff-filter=M --name-only | wc -l | xargs)" >> $GITHUB_OUTPUT
             echo "deleted_count=$(git diff HEAD --diff-filter=D --name-only | wc -l | xargs)" >> $GITHUB_OUTPUT
             git commit -m "Update screenshots [ci skip]"
-            git push origin HEAD:${{ steps.vars.outputs.vrt_diff_temp_branch }} -f
+            git push origin HEAD:${{ needs.init.outputs.vrt_diff_temp_branch }} -f
             echo "changed_snapshots_url=https://github.com/${{ inputs.vrt_repo }}/commit/$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
           fi
         id: results
-        if: github.event_name == 'pull_request'
       - name: Create or update comment
         uses: actions/github-script@v7
         with:
@@ -205,9 +309,3 @@ jobs:
               });
             }
         if: github.event_name == 'pull_request'
-      - name: Upload test-results on failure for debug
-        uses: actions/upload-artifact@v4
-        with:
-          name: test-results
-          path: test-results
-        if: failure()
